server:
  port: 8000

spring:
  application:
    name: api-gateway

  security: 
    oauth2:
      client:
        registration:
          keyclock:
            client-id: springboot-oauth-spa
            client-secret: ccokqghgufDfXmLuoLOj6RoYs8XaRGIe
            scope: openid, email, profile 
            redirect-uri: http://localhost:3000/callback
          provider:
            keyclock:
              issur-uri: http://localhost:8080/realms/master

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - Tokenrelay= 
            - CircuitBreaker=authCircuitBreaker,/auth-fallback
            - SetPath=/fallback/auth

        - id: budget-service
          uri: lb://budget-service
          predicates:
            - Path=/budget/**
          filters:
            - CircuitBreaker=budgetCircuitBreaker,/budget-fallback
            - PrefixPath=/budget
            - SetPath=/fallback/budget
        
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/category/**
          filters:
            - CircuitBreaker=categoryCircuitBreaker,/category-fallback
            - PrefixPath=/category
            - SetPath=/fallback/category
        
        - id: currency-service
          uri: lb://currency-service
          predicates:
            - Path=/currency/**
          filters:
            - CircuitBreaker=currencyCircuitBreaker,/currency-fallback
            - PrefixPath=/currency
            - SetPath=/fallback/currency
        
        - id: finance-service
          uri: lb://finance-service
          predicates:
            - Path=/finance/**
          filters:
            - CircuitBreaker=financeCircuitBreaker,/finance-fallback
            - PrefixPath=/finance
            - SetPath=/fallback/finance
        
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
          filters:
            - CircuitBreaker=notificationCircuitBreaker,/notification-fallback
            - PrefixPath=/notification
            - SetPath=/fallback/notification
        
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - CircuitBreaker=userCircuitBreaker,/user-fallback
            - PrefixPath=/user
            - SetPath=/fallback/user

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,gateway

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
      springframework:
        security: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
